// src/components/ui/CommandPalette.tsx
import { useState, useEffect, useCallback, useRef, type ReactNode } from "react";
import { useNavigate } from "@tanstack/react-router";
import {
  Search,
  Home,
  Users,
  DollarSign,
  CheckSquare,
  FileText,
  Building2,
  Shield,
  Settings,
  BarChart3,
  ArrowLeftRight,
  Gift,
  CreditCard,
  Globe,
} from "lucide-react";

interface CommandItem {
  id: string;
  label: string;
  icon: ReactNode;
  to?: string;
  action?: () => void;
}

const COMMANDS: CommandItem[] = [
  { id: "dashboard", label: "Dashboard", icon: <Home className="h-4 w-4" />, to: "/app" },
  { id: "members", label: "Members", icon: <Users className="h-4 w-4" />, to: "/app/members" },
  { id: "finance", label: "Finance", icon: <DollarSign className="h-4 w-4" />, to: "/app/finance" },
  {
    id: "attendance",
    label: "Attendance",
    icon: <CheckSquare className="h-4 w-4" />,
    to: "/app/attendance",
  },
  { id: "reports", label: "Reports", icon: <FileText className="h-4 w-4" />, to: "/app/reports" },
  {
    id: "organization",
    label: "Organization",
    icon: <Building2 className="h-4 w-4" />,
    to: "/app/organization",
  },
  { id: "users", label: "Users", icon: <Users className="h-4 w-4" />, to: "/app/users" },
  { id: "audit", label: "Audit Log", icon: <Shield className="h-4 w-4" />, to: "/app/audit" },
  {
    id: "reconciliation",
    label: "Reconciliation",
    icon: <ArrowLeftRight className="h-4 w-4" />,
    to: "/app/reconciliation",
  },
  {
    id: "contributions",
    label: "Contributions",
    icon: <Gift className="h-4 w-4" />,
    to: "/app/contributions",
  },
  {
    id: "settings",
    label: "Settings",
    icon: <Settings className="h-4 w-4" />,
    to: "/app/settings",
  },
  {
    id: "billing",
    label: "Billing",
    icon: <CreditCard className="h-4 w-4" />,
    to: "/app/admin/billing",
  },
  {
    id: "conference",
    label: "Conference Dashboard",
    icon: <BarChart3 className="h-4 w-4" />,
    to: "/app/conference",
  },
  {
    id: "global",
    label: "Global Dashboard",
    icon: <Globe className="h-4 w-4" />,
    to: "/app/global",
  },
];

const RECENT_KEY = "theobase-command-recent";
const MAX_RECENT = 5;

function getRecent(): string[] {
  try {
    return JSON.parse(localStorage.getItem(RECENT_KEY) || "[]");
  } catch {
    return [];
  }
}

function addRecent(id: string) {
  const recent = getRecent().filter((r) => r !== id);
  recent.unshift(id);
  localStorage.setItem(RECENT_KEY, JSON.stringify(recent.slice(0, MAX_RECENT)));
}

export function CommandPalette() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  const filtered = COMMANDS.filter(
    (c) => !query || c.label.toLowerCase().includes(query.toLowerCase())
  );

  const recentIds = getRecent();
  const sorted = [...filtered].sort((a, b) => {
    const aRecent = recentIds.indexOf(a.id);
    const bRecent = recentIds.indexOf(b.id);
    if (aRecent !== -1 && bRecent !== -1) return aRecent - bRecent;
    if (aRecent !== -1) return -1;
    if (bRecent !== -1) return 1;
    return 0;
  });

  useEffect(() => {
    setSelectedIndex(0);
  }, [query]);

  useEffect(() => {
    if (open) {
      inputRef.current?.focus();
      setQuery("");
      setSelectedIndex(0);
    }
  }, [open]);

  const onKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setOpen((v) => !v);
      }
      if (!open) return;
      if (e.key === "Escape") {
        setOpen(false);
      } else if (e.key === "ArrowDown") {
        e.preventDefault();
        setSelectedIndex((i) => Math.min(i + 1, sorted.length - 1));
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setSelectedIndex((i) => Math.max(i - 1, 0));
      } else if (e.key === "Enter") {
        const item = sorted[selectedIndex];
        if (item) {
          e.preventDefault();
          addRecent(item.id);
          setOpen(false);
          if (item.action) {
            item.action();
          } else if (item.to) {
            navigate({ to: item.to });
          }
        }
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [open, sorted, selectedIndex]
  );

  useEffect(() => {
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [onKeyDown]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[200] flex items-start justify-center pt-[15vh]">
      <div className="fixed inset-0 bg-black/50" onClick={() => setOpen(false)} />
      <div className="relative w-full max-w-lg rounded-xl border border-gray-200 bg-white shadow-2xl">
        <div className="flex items-center border-b border-gray-200 px-4 py-3">
          <Search className="mr-2 h-4 w-4 text-gray-400" />
          <input
            ref={inputRef}
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search pages..."
            className="flex-1 text-sm outline-none placeholder:text-gray-400"
          />
          <kbd className="rounded border border-gray-200 bg-gray-50 px-1.5 py-0.5 text-[10px] font-medium text-gray-400">
            ESC
          </kbd>
        </div>
        <div className="max-h-72 overflow-y-auto p-2">
          {sorted.length === 0 ? (
            <p className="px-3 py-6 text-center text-sm text-gray-500">No results</p>
          ) : (
            sorted.map((item, i) => (
              <button
                key={item.id}
                onClick={() => {
                  addRecent(item.id);
                  setOpen(false);
                  if (item.action) item.action();
                  else if (item.to) navigate({ to: item.to });
                }}
                className={`flex w-full items-center gap-3 rounded-md px-3 py-2 text-sm transition-colors ${
                  i === selectedIndex
                    ? "bg-gray-100 text-gray-900"
                    : "text-gray-700 hover:bg-gray-50"
                }`}
              >
                <span className="flex h-6 w-6 items-center justify-center text-gray-500">
                  {item.icon}
                </span>
                <span className="flex-1 text-left">{item.label}</span>
                {recentIds.includes(item.id) && (
                  <span className="text-[10px] text-gray-400">Recent</span>
                )}
              </button>
            ))
          )}
        </div>
      </div>
    </div>
  );
}

// apps/web/src/lib/components/CommandPalette.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { visibleSections } from "$lib/nav";
  import { cn } from "$lib/utils";
  import Search from "@lucide/svelte/icons/search";

  interface Props {
    roles?: string[];
    open: boolean;
    onOpenChange?: (open: boolean) => void;
  }

  let { roles = [], open = false, onOpenChange }: Props = $props();

  let query = $state("");
  let selectedIndex = $state(0);
  let inputEl = $state<HTMLInputElement>();

  const sections = $derived(visibleSections(roles));
  const allItems = $derived(
    sections.flatMap((s) =>
      s.items.map((item) => ({ ...item, section: s.label })),
    ),
  );

  const filtered = $derived(
    query.trim()
      ? allItems.filter(
          (item) =>
            item.label.toLowerCase().includes(query.toLowerCase()) ||
            item.section.toLowerCase().includes(query.toLowerCase()),
        )
      : allItems.slice(0, 8),
  );

  $effect(() => {
    selectedIndex = 0;
    if (open) {
      query = "";
      setTimeout(() => inputEl?.focus(), 50);
    }
  });

  function navigate(href: string) {
    onOpenChange?.(false);
    goto(href);
  }

  function close() {
    onOpenChange?.(false);
  }

  function handleKeydown(e: KeyboardEvent) {
    if (!open) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      selectedIndex = Math.min(selectedIndex + 1, filtered.length - 1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      selectedIndex = Math.max(selectedIndex - 1, 0);
    } else if (e.key === "Enter" && filtered[selectedIndex]) {
      e.preventDefault();
      navigate(filtered[selectedIndex].href);
    } else if (e.key === "Escape") {
      close();
    }
  }
</script>

<svelte:window onkeydown={handleKeydown} />

{#if open}
  <div class="fixed inset-0 z-50">
    <button
      class="fixed inset-0 bg-black/40 backdrop-blur-sm cursor-default"
      onclick={close}
      aria-label="Close command palette"
    ></button>
    <div
      class="fixed left-1/2 top-[20%] z-50 w-full max-w-lg -translate-x-1/2 overflow-hidden rounded-xl bg-white shadow-2xl ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-700"
      role="dialog"
      aria-modal="true"
      aria-label="Command palette"
    >
      <div class="flex items-center border-b border-slate-200 dark:border-slate-700 px-4">
        <Search class="size-4 shrink-0 text-slate-400" />
        <input
          type="text"
          placeholder="Search pages..."
          class="flex-1 border-0 bg-transparent px-3 py-4 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none dark:text-slate-100 dark:placeholder:text-slate-500"
          bind:value={query}
          bind:this={inputEl}
          autofocus
        />
        <kbd class="hidden rounded border border-slate-200 px-1.5 py-0.5 text-[10px] text-slate-400 dark:border-slate-700 sm:inline-block">esc</kbd>
      </div>
      <div class="max-h-80 overflow-y-auto p-2">
        {#if filtered.length === 0}
          <p class="px-3 py-6 text-center text-sm text-slate-400">No pages found.</p>
        {:else}
          {#each filtered as item, i}
            {@const Icon = item.icon}
            <button
              class={cn(
                "flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-colors",
                i === selectedIndex
                  ? "bg-brand-50 text-brand-900 dark:bg-brand-950 dark:text-brand-200"
                  : "text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800",
              )}
              onclick={() => navigate(item.href)}
            >
              <Icon class="size-4 shrink-0" />
              <span class="flex-1 text-left">{item.label}</span>
              <span class="text-xs text-slate-400 dark:text-slate-500">{item.section}</span>
            </button>
          {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}
